name: CI

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

jobs:
    appimage:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y cmake qtbase5-dev qtmultimedia5-dev qtdeclarative5-dev qtquickcontrols2-5-dev libexiv2-dev fuse libfuse2 wget
            - name: Build
              run: |
                  mkdir build
                  cd build
                  cmake ..
                  make -j$(nproc)
            - name: Download linuxdeployqt
              run: |
                  wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
                  chmod a+x linuxdeployqt-continuous-x86_64.AppImage
            - name: Create AppImage
              run: |
                  cd build
                  cp ../resources/lumixor.desktop lumixor-qt.desktop
                  cp ../resources/lumixor.svg lumixor-qt.svg
                  ../linuxdeployqt-continuous-x86_64.AppImage lumixor-qt -appimage -no-translations -no-copy-copyright-files
            - name: Upload AppImage
              uses: actions/upload-artifact@v4
              with:
                  name: Lumixor-AppImage
                  path: build/*.AppImage
